// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTm6dQqgXeQxQ5hmMd8nPajrFFPCJR7bs',
    appId: '1:1083681645977:web:e1617ad3edf2aa9c0e9f08',
    messagingSenderId: '1083681645977',
    projectId: 'labpapers-4db23',
    authDomain: 'labpapers-4db23.firebaseapp.com',
    storageBucket: 'labpapers-4db23.firebasestorage.app',
    measurementId: 'G-NN8DQMXQRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUEmMQGLb8J4knX3-HtUZdVVG9INOts5g',
    appId: '1:1083681645977:android:897de468f5d54b020e9f08',
    messagingSenderId: '1083681645977',
    projectId: 'labpapers-4db23',
    storageBucket: 'labpapers-4db23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJ9KXWww3193Pg6SERpfF58ojbRBzw14',
    appId: '1:1083681645977:ios:6e3e2cf05c6eaf4c0e9f08',
    messagingSenderId: '1083681645977',
    projectId: 'labpapers-4db23',
    storageBucket: 'labpapers-4db23.firebasestorage.app',
    iosBundleId: 'com.example.papers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJ9KXWww3193Pg6SERpfF58ojbRBzw14',
    appId: '1:1083681645977:ios:6e3e2cf05c6eaf4c0e9f08',
    messagingSenderId: '1083681645977',
    projectId: 'labpapers-4db23',
    storageBucket: 'labpapers-4db23.firebasestorage.app',
    iosBundleId: 'com.example.papers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTm6dQqgXeQxQ5hmMd8nPajrFFPCJR7bs',
    appId: '1:1083681645977:web:718dd686d413e8720e9f08',
    messagingSenderId: '1083681645977',
    projectId: 'labpapers-4db23',
    authDomain: 'labpapers-4db23.firebaseapp.com',
    storageBucket: 'labpapers-4db23.firebasestorage.app',
    measurementId: 'G-X03B4LLW18',
  );
}
